/*
 *
 * CustomerDetail constants
 *
 */

import { createActionType } from 'utils/reduxHelper';

export const CONTEXT = 'STG/CUSTOMER_DETAIL';

export const GET_ORDER_LIST = `${CONTEXT}/GET_ORDER_LIST`;
export const GET_PROFILE = `${CONTEXT}/GET_PROFILE`;
export const CLEAN_DATA = `${CONTEXT}/CLEAN_DATA`;
export const GET_WALLET = `${CONTEXT}/GET_WALLET`;
export const UPDATE_WALLET = `${CONTEXT}/UPDATE_WALLET`;
export const GET_WALLET_TRANSACTIONS = `${CONTEXT}/GET_WALLET_TRANSACTIONS`;
export const GET_USER_ADDRESS = `${CONTEXT}/GET_USER_ADDRESS`;
export const GET_ADDRESS_DETAIL = `${CONTEXT}/GET_ADDRESS_DETAIL`;
export const CLEAR_ADDRESS_DETAIL = `${CONTEXT}/CLEAR_ADDRESS_DETAIL`;

export const [
  GET_ORDER_LIST_REQUEST,
  GET_ORDER_LIST_SUCCESS,
  GET_ORDER_LIST_FAIL,
] = createActionType(GET_ORDER_LIST);
export const [
  GET_PROFILE_REQUEST,
  GET_PROFILE_SUCCESS,
  GET_PROFILE_FAIL,
] = createActionType(GET_PROFILE);

export const [
  GET_WALLET_REQUEST,
  GET_WALLET_SUCCESS,
  GET_WALLET_FAIL,
] = createActionType(GET_WALLET);

export const [
  UPDATE_WALLET_REQUEST,
  UPDATE_WALLET_SUCCESS,
  UPDATE_WALLET_FAIL,
] = createActionType(UPDATE_WALLET);

export const [
  GET_WALLET_TRANSACTIONS_REQUEST,
  GET_WALLET_TRANSACTIONS_SUCCESS,
  GET_WALLET_TRANSACTIONS_FAIL,
] = createActionType(GET_WALLET_TRANSACTIONS);

export const [
  GET_USER_ADDRESS_REQUEST,
  GET_USER_ADDRESS_SUCCESS,
  GET_USER_ADDRESS_FAIL,
] = createActionType(GET_USER_ADDRESS);

export const [
  GET_ADDRESS_DETAIL_REQUEST,
  GET_ADDRESS_DETAIL_SUCCESS,
  GET_ADDRESS_DETAIL_FAIL,
] = createActionType(GET_ADDRESS_DETAIL);

export const LOADING_ACTION_TYPES = [GET_PROFILE, UPDATE_WALLET];
